### ISSUE TITLE
Unable to view large graphs mapped to reference

### ISSUE THREAD

**Issue by rozovr** [olga24912/bio_scaffolder#4]
I'm trying to view a mapping of contigs to a reference, where the reference is about 2G. During the run, SGTK reports "GRAPH is too big... Small edges deletion." and reduces the number of edges to around 400k. I can view the graph in "Free(Dagre) Layout" with no problem, but when I try the Genome Browser option both Chrome and Firefox fail to display it. 
Chrome on OSX just shows me an "Aw Snap, failed to load" message, and on Linux I see lines like "tcmalloc: large alloc 1073745920 bytes == 0x3488e1a4a000 @  0x55b273c48f5a 0x55b272ee5ec8 0.." printed on the terminal. 
Firefox on linux prints "(firefox:19276): Gdk-WARNING **: /build/gtk+3.0-PCLr8A/gtk+3.0-3.18.9/./gdk/x11/gdkproperty-x11.c:224 invalid X atom: 1883306368"

I've also tried mapping to only one chromosome to reduce memory requirements, but observed similar behavior. Can you please advise how to make the mapping to the genome work?

Many thanks and congrats on the excellent tool, Roye

**Comment by olga24912** [comment]
Hi Roye,

Thank you for your time and comments! Sorry for the delayed answer.

I've just uploaded a new version (1.2) to Anaconda (as well as GitHub release). It includes some performance updates. Would you mind checking if that fixes the issue for you?
