### ISSUE TITLE
AttributeError: 'Seq' object has no attribute 'tostring'

### ISSUE THREAD

**Issue by ZhangDengwei** [olga24912/bio_scaffolder#6]
Hi,

I have installed the minimap2, biopython, and SGTK separately. The following is the command:

`nohup sgtk.py --contigs ../contig.fa --fr ../../../01.fastp/H13_r1.fq.gz ../../../01.fastp/H13_r2.fq.gz --ref ../../../09.genome_pairwise_alignment/GCF_000010245.2_ASM1024v1_genomic.fna -o ./ &`

But I encountered an error as follows:

`OUTPUT DIR: /home/dengwei/project/20200522_AirCon2/02.Genome_assembly/H13_4/sgtk/tmp/
MKDIR
START ALIG: fr_0
START BUILD GRAPH: fr_0
Traceback (most recent call last):
  File "/home/dengwei/toolkit/SGTK-1.4.1-Linux/bin/sgtk.py", line 1120, in <module>
    run(args)
  File "/home/dengwei/toolkit/SGTK-1.4.1-Linux/bin/sgtk.py", line 1090, in run
    gen_id_from_contig_file(contig_file_name)
  File "/home/dengwei/toolkit/SGTK-1.4.1-Linux/bin/sgtk.py", line 491, in gen_id_from_contig_file
    name, lenn = fasta.id, len(fasta.seq.tostring())
AttributeError: 'Seq' object has no attribute 'tostring'
`
Any advice would be appreciated.

**Comment by ZhangDengwei** [comment]
I have addressed it. This error is due to the update of biopython. Please change the code-fasta.seq.tostring()-in line 491 to str(fasta.seq), then it will work

**Comment by olga24912** [comment]
Hi, 

Thank you for using SGTK and for the bug report! I have fixed the bug and released version 1.4.2. 

Any other bug reports are appreciated.  

Best, 
Olga
